services:
  samba:
    image: ${DOCKER_REGISTRY}samba:${DOCKER_TAG:-latest}
    restart: unless-stopped
    environment:
      WORKGROUP: "${WORKGROUP}"
      USERS: "${USERS}"
    ports:
      - "445:445"
    volumes:
      - "samba-data:/samba"

volumes:
  samba-data:
    name: "${VOLUME:?}"
